# -*- coding: utf-8 -*-
"""scrapping_imdb_distributors(다연).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lh989dfj-oaP5XqX7v04LUM8T2vkddis
"""

# prd_company imdb 스크래핑 코드
def scrp_prd_company():
  from bs4 import BeautifulSoup
  import requests
  import pandas as pd
  import re

  meta=pd.read_csv('mv_id.csv',engine='python')
  mv_id=meta['movie_id'].to_list()

  movie_id=[]
  year=[]
  country=[]
  types=[]
  company=[]

  for i in range(len(mv_id)):
    url='https://www.imdb.com/title/{}/companycredits?ref_=tt_dt_co'.format(mv_id[i])
    resp=requests.get(url)
    html=resp.text
    soup=BeautifulSoup(html,'html5lib')
    l=soup.select('#company_credits_content > ul:nth-of-type(2) > li')

    ls=''
    ls_1=''
    for j in l:
      ls=(j.text)
      result = re.findall('\(([^)]+)', ls)
      if len(result) > 1:
        if result[1]=='USA':
          result0=re.sub('\(([^)]+)','',ls)
          result0_0=re.sub('\)','',result0)
          result1=re.findall('\w+\+?\.?\!?\s.+',result0_0)
          company.append(result1)
          movie_id.append(mv_id[i])
          year.append(result[0])
          country.append(result[1])
          types.append(result[2])
        elif result[1]=='World-wide':
          result0=re.sub('\(([^)]+)','',ls)
          result0_0=re.sub('\)','',result0)
          result1=re.findall('\w+\+?\.?\!?\s.+',result0_0)
          company.append(result1)
          movie_id.append(mv_id[i])
          year.append(result[0])
          country.append(result[1])
          types.append(result[2])
        else:
          pass

  company_ls=[]
  company_str=''
  for i in company:
      company_str=i[0].strip()
      company_ls.append(company_str)

  scrp_prd_company=pd.DataFrame({'movie_id':movie_id,
                                'company':company_ls,
                                'year':year,
                                'country':country,
                                'types':types})

  scrp_prd_company.to_csv('scrp_prd_company.csv')
# scrp_prd_company()

